### ISSUE TITLE
text_sensor not updated when using state_machine.set

### ISSUE THREAD

**Issue by nicochi** [muxa/esphome-state-machine#19]
text_sensor is not updated when state is set using state_machine.set without a transition.

This is used for example when changing state after reboot and the state is set based on a binary sensor. See for exampe your garage.yaml example and init code in API status.

**Comment by muxa** [comment]
Fixed in https://github.com/muxa/esphome-state-machine/releases/tag/1.0.0-rc.9. Thanks @nicochi for reporting!
