### ISSUE TITLE
How to get current state in lambda? 

### ISSUE THREAD

**Issue by spuder** [muxa/esphome-state-machine#42]
Thank you for providing this code. 

I'm trying to `set` and `get` the current state_machine state from a lambda. 

I can _set_ the transition from a lambda, but I can't _read_ the state from a lambda. 

Setting the transition works: 
```cpp
id(state_machine_mode).transition("ERROR");
```

However attempting to get the state returns this error

```cpp
if (id(state_machine_mode).state != "ERROR") {
  
}
```

```bash
error: 'class esphome::state_machine::StateMachineComponent' has no member named 'state'; did you mean 'states_'?
```

Is it possible to get the state from a lambda? If so what is the syntax

**Comment by muxa** [comment]
To get the current state from lambda use `current_state()`, e.g. `id(state_machine_mode).current_state()`
